// Mocks generated by Mockito 5.4.6 from annotations
// in doctors_doc/test/features/auth/domain/auth_repos_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:doctors_doc/core/errors/failuer.dart' as _i5;
import 'package:doctors_doc/features/auth/domain/entities/client_info_entity.dart'
    as _i7;
import 'package:doctors_doc/features/auth/domain/entities/clinet_response_entity.dart'
    as _i6;
import 'package:doctors_doc/features/auth/domain/repositories/auth_repos.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepos].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepos extends _i1.Mock implements _i3.AuthRepos {
  MockAuthRepos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>> registerClinet(
    _i7.ClientInfoEntity? clientInfoEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerClinet, [clientInfoEntity]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failuer, _i6.ClinetResponseEntity>(
                    this,
                    Invocation.method(#registerClinet, [clientInfoEntity]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>> loginClinet({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginClinet, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failuer, _i6.ClinetResponseEntity>(
                    this,
                    Invocation.method(#loginClinet, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>>);
}

/// A class which mocks [AuthRepos].
///
/// See the documentation for Mockito's code generation for more information.
class MocksAuthRepos extends _i1.Mock implements _i3.AuthRepos {
  MocksAuthRepos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>> registerClinet(
    _i7.ClientInfoEntity? clientInfoEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerClinet, [clientInfoEntity]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failuer, _i6.ClinetResponseEntity>(
                    this,
                    Invocation.method(#registerClinet, [clientInfoEntity]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>> loginClinet({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginClinet, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>
                >.value(
                  _FakeEither_0<_i5.Failuer, _i6.ClinetResponseEntity>(
                    this,
                    Invocation.method(#loginClinet, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failuer, _i6.ClinetResponseEntity>>);
}
