
platform :android do
    desc "upload a build to Firebase App Distribution"
    lane :deploy_to_firebase_app_distribution do
        sh "flutter clean"
        sh "flutter build apk --release --no-tree-shake-icons"
        release = firebase_app_distribution(
            app: "1:482664002625:android:579889bf8f97fd1c8742c0",
            firebase_cli_token:Env["CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
            testers: "elsaramegymahmoud404@gmail.com,",
            release_notes: "auth future version"
        )
    end
end